<?php
    require_once dirname(__FILE__) .'/pdo.php';
    $CURRENT_LOCATION_INFORMATION = getOne("select CURRENT_LOCATION_INFORMATION from DEVICE_LIST where DEVICE_ID='359339075000861'");
    echo $CURRENT_LOCATION_INFORMATION;